name: checkers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run tests with coverage
        run: |
          pytest --cov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.1.0
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
